#there's some dicts that are used

specialist_dict = {
        'acupuntu' : 'ACUPUNTURISTA',
        'alergia e imunologia' : 'ALERGIA E IMUNOLOGIA',
        'aneste' : 'ANESTESIOLOGIA',
        'angiologia' : 'ANGIOLOGIA',
        'cardiol' : 'CARDIOLOGISTA',
        'cirurgia cardiovascular' : 'CIRURGIA CARDIOVASCULAR',
        'cardiovascular' : 'CIRURGIA CARDIOVASCULAR',
        'cirurgia da mao' : 'CIRURGIA DA MÃO',
        'cirurgiao de cabeca e pescoco' : 'CIRURGIÃO DE CABEÇA E PESCOÇO',
        'cirurgia de cabeca e pescoco' : 'CIRURGIÃO DE CABEÇA E PESCOÇO',
        'cirurgiao cabeca e pescoco' : 'CIRURGIÃO DE CABEÇA E PESCOÇO',
        'cirurgia cabeca e pescoco' : 'CIRURGIÃO DE CABEÇA E PESCOÇO',
        'cirurgia do aparelho digestivo' : 'CIRURGIA DO APARELHO DIGESTIVO',
        'cirurgia geral' : 'CIRURGIA GERAL',
        'cirurgia oncologica' : 'CIRURGIA ONCOLÓGICA',
        'cirurgia pediatrica' : 'CIRURGIA PEDIÁTRICA',
        'cirurgiao pediatri' : 'CIRURGIA PEDIÁTRICA',
        'cirurgiao plastico' : 'CIRURGIÃO PLÁSTICO',
        'cirurgia plastica' : 'CIRURGIÃO PLÁSTICO',
        'cirurgia torácica' : 'CIRURGIA TORÁCICA',
        'cirurgia vascular' : 'CIRURGIA VASCULAR',
        'clinica medica' : 'CLÍNICO',
        'clinico' : 'CLÍNICO',
        'coloproctologia' : 'COLOPROCTOLOGIA ',
        'dermato' : 'DERMATOLOGISTA',
        'endocrino' : 'ENDÓCRINOLOGISTA',
        'endoscopia' : 'ENDOSCOPIA',
        'fonoaud' : 'FONOAUDIOLOGIA',
        'gastro' : 'GASTROENTEROLOGIA',
        'genetica medica' : 'GENÉTICA MÉDICA',
        'geriatria' : 'GERIATRIA',
        'ginecologi' : 'GINECOLOGIA',
        'hemato' : 'HEMATOLOGISTA',
        'hemotera' : 'HEMATOLOGISTA',
        'hepat' : 'HEPATOLOGISTA',
        'homeopat' : 'HOMEOPATA',
        'infecto' : 'INFECTOLOGISTA',
        'mastolo' : 'MASTOLOGISTA',
        'medicina de emergencia' : 'MEDICINA DE EMERGÊNCIA',
        'medicina de familia' : 'MEDICINA DE FAMÍLIA',
        'medicina do trabalho' : 'MEDICINA DO TRABALHO',
        'medicina de trafego' : 'MEDICINA DE TRÁFEGO',
        'medicina esportiva' : 'MEDICINA ESPORTIVA',
        'medicina fisica e reabilitacao' : 'MEDICINA FÍSICA E REABILITAÇÃO',
        'medicina intensiva' : 'MEDICINA INTENSIVA',
        'medicina legal e pericia medica' : 'MEDICINA LEGAL E PERÍCIA MÉDICA',
        'medicina nuclear' : 'MEDICINA NUCLEAR',
        'medicina preventiva' : 'MÉDICO DE FAMÍLIA',
        'nefrolog' : 'NEFROLOGISTA',
        'neurocirurg' : 'NEUROLOGISTA',
        'neurol' : 'NEUROLOGISTA',
        'nutrologia' : 'NUTROLOGIA',
        'nutricio' : 'NUTROLOGIA',
        'oftalmo' : 'OFTALMOLOGISTA',
        'oncol' : 'ONCOLOGISTA',
        'ortoped' : 'ORTOPEDISTA',
        'otorrino' : 'OTORRINOLARINGOLOGIA',
        'odonto' : 'ODONTOLOGISTA',
        'patolog' : 'PATOLOGIA',
        'obstetr' : 'OBSTETRA',
        'patologia clínica/medicina laboratorial' : 'PATOLOGIA CLÍNICA/MEDICINA LABORATORIAL',
        'pediatr' : 'PEDIATRIA',
        'pneumolog' : 'PNEUMOLOGISTA',
        'psiquiat' : 'PSIQUIATRIA',
        'psicol' : 'PSICOLOGIA',
        'radiolog' : 'RADIOLOGIA E DIAGNÓSTICO POR IMAGEM',
        'radioterapia' : 'RADIOTERAPIA',
        'reumatolo' : 'REUMATOLOGISTA ',
		'servico social' : 'SERVIÇO SOCIAL',
		'assistente social' : 'ASSISTÊNCIA SOCIAL',
        'urolog' : 'UROLOGISTA',
    }

neglecteddiseases_dict = {
    'malaria' : 'MALÁRIA',
    'doença de Chagas' : 'DOENÇA DE CHAGAS',
    'leishmaniose' : 'LEISHMANIOSE',
    'tuberculose' : 'TUBERCULOSE',
    'dengue' : 'DENGUE',
    'hanseniase' : 'HANSENÍASE',
    'esquistossomose' : 'ESQUISTOSSOMOSE',
    'oncocercose' : 'ONCOCERCOSE',
    'filariose' : 'FILARIOSE',
    'tracoma' : 'TRACOMA',
    'helmintos' : 'HELMINTOS',
    'nematoides de solo' : 'NEMATÓIDES DE SOLO'
}

conditionsensitive_dict = {

    'coqueluche' : 'COQUELUCHE',
    'difteria' : 'DIFTERIA',
    'tetano' : 'TÉTANO',
    'parotidite' : 'PAROTIDITE',
    'rubeola' : 'RUBÉOLA',
    'sarampo' : 'SARAMPO',
    'febre amarela' : 'FEBRE AMARELA',
    'hepatite b' : 'HEPATITE B',
    'meningite por haemophilus' : 'MENINGITE POR HAEMOPHILUS',
    'meningite tuberculosa' : 'MENINGITE TUBERCULOSA',
    'meningite' : 'MENINGITE',
    'tuberculose miliar' : 'TUBERCULOSE MILIAR',
    'tuberculose pulmonar' : 'TUBERCULOSE PULMONAR',
    'tuberculose' : 'TUBERCULOSE',
    'tb' : 'TUBERCULOSE',
    'febre reumatica' : 'FEBRE REUMÁTICA',
    'sifilis congenita' : 'SÍFILIS CONGÊNITA',
    'sifilis' : 'SÍFILIS',
    'malaria' : 'MALÁRIA',
    'ascaridiase' : 'ASCARIDÍASE',
    'desidratacao' : 'DESIDRATAÇÃO',
    'gastroenterite' : 'GASTROENTERITE',
    'anemia por deficiencia de ferro' : 'ANEMIA POR DEFICIÊNCIA DE FERRO',
    'anemia' : 'ANEMIA',
    'otite media supurativa' : 'OTITE MÉDIA SUPURATIVA',
    'nasofaringite aguda' : 'RESFRIADO COMUM',
    'resfriado' : 'RESFRIADO COMUM',
    'sinusite aguda' : 'SINUSITE AGUDA',
    'sinusite' : 'SINUSITE',
    'faringite aguda' : 'FARINGITE AGUDA',
    'amigdalite aguda' : 'AMIGDALITE AGUDA',
    'infeccao aguda vas' : 'INFECÇÃO AGUDA VAS',
    'rinite' : 'RINITE',    
    'nasofaringite cronica' : 'NASOFARINGITE CRÔNICA',
    'faringite cronica' : 'FARINGITE CRÔNICA',
    'faringite' : 'FARINGITE',
    'pneumonia pneumococica' : 'PNEUMONIA PNEUMOCÓCICA',
    'pneumonia por haemophilus infuenzae' : 'PNEUMONIA POR HAEMOPHILUS INFUENZAE',
    'pneumonia por streptococus' : 'PNEUMONIA POR STREPTOCOCUS',
    'pneumonia bacteriana' : 'PNEUMONIA BACTERIANA NE',
    'pneumonia lobar' : 'PNEUMONIA LOBAR NE',
    'pneumonia' : 'PNEUMONIA',
    'asma' : 'ASMA',
    'bronquite aguda' : 'BRONQUITE AGUDA',
    'bronquite cronica' : 'BRONQUITE CRÔNICA',
    'bronquite' : 'BRONQUITE',
    'enfisema' : 'ENFISEMA',
    'bronquectasia' : 'BRONQUECTASIA',
    'doenca pulmonar' : 'DOENÇAS PULMONARES OBSTRUTIVAS CRÔNICAS',
    'hipertensao essencial' : 'HIPERTENSÃO ESSENCIAL',
    'doenca cardiaca hipertensiva' : 'DOENÇA CARDÍACA HIPERTENSIVA',
    'angina pectoris' : 'ANGINA PECTORIS',
    'insuficiencia cardiaca' : 'INSUFICIÊNCIA CARDÍACA',
    'edema agudo de pulmao' : 'EDEMA AGUDO DE PULMÃO',
    'doenca cerebrovascular' : 'DOENÇA CEREBROVASCULAR',
    'diabetes melitus' : 'DIABETES MELITUS',
    'cistite' : 'EPILEPSIA',
    'nefrite tubulo-intersticial aguda' : 'NEFRITE TÚBULO-INTERSTICIAL AGUDA',
    'nefrite tubulo-intersticial cronica' : 'NEFRITE TÚBULO-INTERSTICIAL CRÔNICA',
    'nefrite tubulo-intersticial ne aguda' : 'NEFRITE TÚBULO-INTERSTICIAL NE AGUDA CRÔNICA',
    'cistite' : 'CISTITE',
    'uretrite' : 'URETRITE',
    'infeccao do trato urinario' : 'INFECÇÃO DO TRATO URINÁRIO',
    'infecção no trato urinario na gravidez' : 'INFECÇÃO NO TRATO URINÁRIO NA GRAVIDEZ',
    'infeccao urina' : 'INFECÇÃO URINÁRIA',
    'erisipela' : 'ERISIPELA',
    'impetigo' : 'IMPETIGO',
    'abscesso cutaneo' : 'ABSCESSO CUTÂNEO',
    'abscesso' : 'ABSCESSO',
    'furunculo' : 'FURÚNCULO',
    'carbunculo' : 'CARBÚNCULO',
    'celulite' : 'CELULITE',
    'linfadenite aguda' : 'LINFADENITE AGUDA',
    'salpingite' : 'SALPINGITE',
    'doenca inflamatoria do utero' : 'OOFORITE',
    'doencas da glandula de bartholin' : 'DOENÇAS DA GLÂNDULA DE BARTHOLIN',
    'ulcera gastrointestinal' : 'ÚLCERA GASTROINTESTINAL',
    'sindrome da rubeola congenita' : 'SÍNDROME DA RUBÉOLA CONGÊNITA'
}

hospital_dict = {
    'spa e policlinica dr. danilo correa' : 'SPA E POLICLÍNICA DR. DANILO CORRÊA',
    'policlinica dr. danilo correa' : 'SPA E POLICLÍNICA DR. DANILO CORRÊA',
    'policlinica danilo correia' : 'SPA E POLICLÍNICA DR. DANILO CORRÊA',
    'policlinica danilo correa' : 'SPA E POLICLÍNICA DR. DANILO CORRÊA',
    '. danilo correa' : 'SPA E POLICLÍNICA DR. DANILO CORRÊA',
    'spa dr. danilo correa' : 'SPA E POLICLÍNICA DR. DANILO CORRÊA',
    'spa danilo correa' : 'SPA E POLICLÍNICA DR. DANILO CORRÊA',
    'pam codajas' : 'POLICLÍNICA CODAJÁS',
    'codajas' : 'POLICLÍNICA CODAJÁS',
    'policlinica codajas' : 'POLICLÍNICA CODAJÁS',
    'pam da codajas' : 'POLICLÍNICA CODAJÁS',
    'fundacao hospital do coracao francisca mendes' : 'FUNDAÇÃO HOSPITAL DO CORAÇÃO FRANCISCA MENDES',
    'francisca mendes' : 'FUNDAÇÃO HOSPITAL DO CORAÇÃO FRANCISCA MENDES',
    'caic moura tapajos' : 'CAIC MOURA TAPAJÓS',
    'caic dr. jose contente' : 'CAIC DR. JOSÉ CONTENTE',
    'spa zona sul' : 'SPA ZONA SUL',
    'caic ana maria dos santos pereira braga' : 'CAIC ANA MARIA DOS SANTOS PEREIRA BRAGA',
    'hospital psiquiatrico eduardo ribeiro' : 'HOSPITAL PSIQUIÁTRICO EDUARDO RIBEIRO',
    'policlinica antônio aleixo' : 'POLICLÍNICA ANTÔNIO ALEIXO',
    'instituto de saude da crianca do amazonas' : 'INSTITUTO DE SAÚDE DA CRIANÇA DO AMAZONAS – ICAM',
    'ican' : 'INSTITUTO DE SAÚDE DA CRIANÇA DO AMAZONAS – ICAM',
    'icam' : 'INSTITUTO DE SAÚDE DA CRIANÇA DO AMAZONAS – ICAM',
    'hospital geral dr. geraldo da rocha' : 'HOSPITAL GERAL DR. GERALDO DA ROCHA',
    'hospital e maternidade chapot prevost' : 'HOSPITAL E MATERNIDADE CHAPOT PREVOST',
    'dr. joao lucio pereira machado' : 'HPS - DR. JOÃO LÚCIO PEREIRA MACHADO',
    'ps joao lucio' : 'HPS - DR. JOÃO LÚCIO PEREIRA MACHADO',
    'h.p.s joao lucio' : 'HPS - DR. JOÃO LÚCIO PEREIRA MACHADO',
    'ps platao araujo' : 'HPS - DR. ARISTÓTELES PLATÃO BEZERRA DE ARAÚJO',
    'platao araujo' : 'HPS - DR. ARISTÓTELES PLATÃO BEZERRA DE ARAÚJO',
    'hps dr. aristoteles platao bezerra de araujo' : 'HPS - DR. ARISTÓTELES PLATÃO BEZERRA DE ARAÚJO',
    'hps platao' : 'HPS - DR. ARISTÓTELES PLATÃO BEZERRA DE ARAÚJO',
    'hps da crianca - zona sul' : 'HPS DA CRIANÇA - ZONA SUL',
    'caimi andre araujo' : 'CAIMI ANDRÉ ARAÚJO',
    'caimi paulo lima' : 'CAIMI PAULO LIMA',
    'maternidade estadual balbina mestrinho' : 'MATERNIDADE ESTADUAL BALBINA MESTRINHO',
    'maternidade azilda da silva marreiro' : 'MATERNIDADE AZILDA DA SILVA MARREIRO',
    'maternidade azilda marreiro' : 'MATERNIDADE AZILDA DA SILVA MARREIRO',
    'spa enfermeira eliameme rodrigues mady' : 'SPA ENFERMEIRA ELIAMEME RODRIGUES MADY',
    'spa coroado' : 'SPA COROADO',
    'spa sao raimundo' : 'SPA SÃO RAIMUNDO',
    'caic dra. maria helena freitas de goes' : 'CAIC DRA. MARIA HELENA FREITAS DE GÓES',
    'caic dr. gilson moreira' : 'CAIC DR. GILSON MOREIRA',
    'caic gilson moreira' : 'CAIC DR. GILSON MOREIRA',
    'caic dr. rubim de sa' : 'CAIC DR. RUBIM DE SÁ',
    'caic jose carlos mestrinho' : 'CAIC JOSÉ CARLOS MESTRINHO',
    'caic dr. edson melo' : 'CAIC DR. EDSON MELO',
    'caic dr. afrânio soares' : 'CAIC DR. AFRÂNIO SOARES',
    'caic alberto carreira' : 'CAIC ALBERTO CARREIRA',
    'caic dra. josephina de mello' : 'CAIC ALEXANDRE MONTORIL',
    'maternidade cidade nova dona nazira daou' : 'MATERNIDADE CIDADE NOVA DONA NAZIRA DAOU',
    'maternidade nazira daou' : 'MATERNIDADE CIDADE NOVA DONA NAZIRA DAOU',
    'spa joventina dias' : 'SPA JOVENTINA DIAS',
    'centro de atencao psicossocial silverio tundis' : 'CENTRO DE ATENÇÃO PSICOSSOCIAL SILVÉRIO TUNDIS',
    'caps silverio tundis' : 'CENTRO DE ATENÇÃO PSICOSSOCIAL SILVÉRIO TUNDIS',
    'hospital infantil dr. fajardo' : 'HOSPITAL INFANTIL DR. FAJARDO',    
    'fajardo' : 'HOSPITAL INFANTIL DR. FAJARDO',
    'policlinica cardoso fontes' : 'POLICLÍNICA CARDOSO FONTES',
    'policlinica ana barreto' : 'POLICLÍNICA ANNA BARRETO PEREIRA',
    'polic. ana  barreto' : 'POLICLÍNICA ANNA BARRETO PEREIRA',
    'polic. ana barreto' : 'POLICLÍNICA ANNA BARRETO PEREIRA',
    'pol. ana barreto' : 'POLICLÍNICA ANNA BARRETO PEREIRA',
    'policlinica anna barreto' : 'POLICLÍNICA ANNA BARRETO PEREIRA',
    'cema' : 'CEMA',
    'lacen' : 'LABORATÓRIO CENTRAL',
    'laboratorio central' : 'LABORATÓRIO CENTRAL',
    'spa e policlinica dr. jose de jesus lins de albuquerque' : 'SPA E POLICLÍNICA DR. JOSÉ DE JESUS LINS DE ALBUQUERQUE',
    'caic alexandre montoril' : 'CAIC ALEXANDRE MONTORIL',
    'caimi ada rodrigues viana' : 'CAIMI ADA RODRIGUES VIANA',
    'cepra' : 'CEPRA',
    'maternidade alvorada' : 'MATERNIDADE ALVORADA',
    'maternidade ana braga' : 'MATERNIDADE ANA BRAGA',
    'fundacao de hematologia e hemoterapia do amazonas' : 'FUNDAÇÃO DE HEMATOLOGIA E HEMOTERAPIA DO AMAZONAS - FHEMOAM',
    'fhemoam' : 'FUNDAÇÃO DE HEMATOLOGIA E HEMOTERAPIA DO AMAZONAS - FHEMOAM',
    'hemoam' : 'FUNDAÇÃO DE HEMATOLOGIA E HEMOTERAPIA DO AMAZONAS - FHEMOAM',
    'hemoan' : 'FUNDAÇÃO DE HEMATOLOGIA E HEMOTERAPIA DO AMAZONAS - FHEMOAM',
    'spa alvorada' : 'SPA ALVORADA',
    'policlinica zeno lanzini' : 'POLICLÍNICA ZENO LANZINI',
    'policlinica joao dos santos braga' : 'POLICLÍNICA JOÃO DOS SANTOS BRAGA',
    'hps 28 de agosto' : 'HPS 28 DE AGOSTO',
    'hps 28  de agosto' : 'HPS 28 DE AGOSTO',
    '28 de agosto' : 'HPS 28 DE AGOSTO',
    'policlinica gilberto mestrinho' : 'POLICLÍNICA GOVERNADOR GILBERTO MESTRINHO',
    'policlinica governador gilberto mestrinho' : 'POLICLÍNICA GOVERNADOR GILBERTO MESTRINHO',
    'pol. gilberto mestrinho' : 'POLICLÍNICA GOVERNADOR GILBERTO MESTRINHO',    
    'polic.gilberto mestrinho' : 'POLICLÍNICA GOVERNADOR GILBERTO MESTRINHO',
    'hps da crianca zona leste' : 'HPS DA CRIANÇA - ZONA LESTE',
    'hps da crianca zona oeste' : 'HPS DA CRIANÇA - ZONA OESTE',
    'hps da crianca zona sul' : 'HPS DA CRIANÇA - ZONA SUL',
    'hps zona sul' : 'HPS DA CRIANÇA - ZONA SUL',
    'fcecon' : 'FUNDAÇÃO CECON',
    'fundacao cecon' : 'FUNDAÇÃO CECON',
    'hospital universitario getulio vargas' : 'HOSPITAL UNIVERSITÁRIO GETÚLIO VARGAS – HUGV',
    'hugv' : 'HOSPITAL UNIVERSITÁRIO GETÚLIO VARGAS – HUGV',
    'huvg' : 'HOSPITAL UNIVERSITÁRIO GETÚLIO VARGAS – HUGV',
    'araujo lima' : 'HOSPITAL UNIVERSITÁRIO GETÚLIO VARGAS – HUGV',
    'fundacao de medicina tropical' : 'FUNDAÇÃO DE MEDICINA TROPICAL – FMT',
    'fmt' : 'FUNDAÇÃO DE MEDICINA TROPICAL – FMT',
    'adriano jorge' : 'FUNDAÇÃO HOSPITAL ADRIANO JORGE – FHAJ',
    'fundacao adriano jorge' : 'FUNDAÇÃO HOSPITAL ADRIANO JORGE – FHAJ',
    'fundacao hospital adriano jorge' : 'FUNDAÇÃO HOSPITAL ADRIANO JORGE – FHAJ',
    'fhaj' : 'FUNDAÇÃO HOSPITAL ADRIANO JORGE – FHAJ',
    'hfaj' : 'FUNDAÇÃO HOSPITAL ADRIANO JORGE – FHAJ',
    'alfredo da mata' : 'FUNDAÇÃO ALFREDO DA MATTA – FAM',
    'fundacao alfredo da matta' : 'FUNDAÇÃO ALFREDO DA MATTA – FAM',
    'fundacao universitaria alfredo da mata' : 'FUNDAÇÃO ALFREDO DA MATTA – FAM',
    'fundacao universitaria alfredo da matta' : 'FUNDAÇÃO ALFREDO DA MATTA – FAM',
    'fundacao de vigilância em saude do amazonas - dra. rosemary costa pinto' : 'FUNDAÇÃO DE VIGILÂNCIA EM SAÚDE DO AMAZONAS - DRA. ROSEMARY COSTA PINTO',
    'instituto da mulher dona lindu' : 'INSTITUTO DA MULHER DONA LINDÚ',
    'instituto da mulher' : 'INSTITUTO DA MULHER DONA LINDÚ',
    'hospital delphina aziz' : 'HOSPITAL DELPHINA AZIZ',
    'delfina aziz' : 'HOSPITAL DELPHINA AZIZ',
    'delphina aziz' : 'HOSPITAL DELPHINA AZIZ',
    'delphina abdel rinald aziz' : 'HOSPITAL DELPHINA AZIZ',
    'delphina rinaldi aziz' : 'HOSPITAL DELPHINA AZIZ',
    'upa campos sales' : 'UPA CAMPOS SALES',
    'upa jose rodrigues' : 'UPA JOSÉ RODRIGUES',
    'ubs' : 'UBS',
    'hapvida' : 'HAPVIDA',
    'hapclinica' : 'HAPVIDA',
    'hospital rio negro' : 'HAPVIDA',
    'sensumed' : 'SENSUMED',
    'semsumed' : 'SENSUMED',
    'sesumed' : 'SENSUMED',
    'check up' : 'CHECK UP',
    'hospital santo alberto' : 'HOSPITAL SANTO ALBERTO',
    'hospital beneficente portuguesa' : 'HOSPITAL BENEFICENTE PORTUGUESA',
    'beneficente portuguesa' : 'HOSPITAL BENEFICENTE PORTUGUESA',
    'h.b.portuguesa' : 'HOSPITAL BENEFICENTE PORTUGUESA',
    'hosp.benef. portuguesa' : 'HOSPITAL BENEFICENTE PORTUGUESA',
    'hospital adventista' : 'HOSPITAL ADVENTISTA',
    'hospital santa julia' : 'HOSPITAL SANTA JÚLIA',
    'instituto de oftalmologia de manaus' : 'INSTITUTO DE OFTALMOLOGIA DE MANAUS - IOM',
    'iom' : 'INSTITUTO DE OFTALMOLOGIA DE MANAUS - IOM',
    'hps' : 'HPS',
    'spa' : 'SPA',
    'caic' : 'CAIC',
    'caimi' : 'CAIMI',
    'upa' : 'UPA',
    'maternidade' : 'MATERNIDADE',
    'poloclinica' : 'POLICLÍNICA'
}

ethnicity_dict = {
    'bare' : 'Baré',
    'bara' : 'Baré',
    'kuripaco' : 'Koripako',
    'hupda' : 'Hupda',
    'ticuna' : 'Tikuna',
    'mura' : 'Mura',
    'satere' : 'Sateré Mawé',
    'kocama' : 'Kokama',
    'munduruku' : 'Munduruku',
    'maragua' : 'Maraguá',
    'paumari' : 'Paumari',
    'apurina' : 'Apurinã',
    'matis' : 'Matis',
    'marubo' : 'Marubo',
    'curipaco' : 'Koripako',
    'yanomami' : 'Yanomami',
    'baniwa' : 'Baniwa',
    'tariano' : 'Tariana',
    'nadeb' : 'Nadöb',
    'dessana' : 'Desana',
    'tukano' : 'Tukano',
    'piratapuia' : 'Pira-tapuya',
    'werekena' : 'Warekena',
    'maku nadeb' : 'Nadöb',
    'tuyuca' : 'Tuyuka',
    'dessano' : 'Desana',
    'kokama' : 'Kokama',
    'tikuna' : 'Tikuna',
    'tenharim' : 'Tenharim',
    'piraha' : 'Pirahã',
    'mundurucu' : 'Munduruku',
    'tora' : 'Torá',
    'jarawara' : 'Jarawara',
    'banawa' : 'Banawá',
    'kanamari' : 'Kanamari',
    'banaewa' : 'Baniwa',
    'kulina' : 'Kulina',
    'culina' : 'Kulina',
    'miranha' : 'Miranha',
    'satere mawe' : 'Sateré Mawé',
    'korubo' : 'Korubo',
    'tucano' : 'Tukano',
    'werekene' : 'Warekena',
    'tiyuka' : 'Tuyuka',
    'hexkaryana' : 'Hixkaryana',
    'tenharin' : 'Tenharim',
    'sarere' : 'Sateré Mawé',
    'deni' : 'Deni',
    'dow' : 'Dâw',
    '01/11/1977' : '?',
    'kambeba' : 'Kambeba',
    'jamamadi' : 'Jamamadi',
    'nao consta' : '?',
    'bara' : 'Bará',
    'tuyuka' : 'Tuyuka',
    'tikuna ' : 'Tikuna',
    'satera' : 'Sateré Mawé',
    'kanamary' : 'Kanamari',
    'daw' : 'Dâw',
    'curupaco' : 'Koripako',
    'piratupaia' : 'Pira-tapuya',
    'icuripaco' : 'Koripako',
    'cubeu' : 'Kubeo',
    'werequina' : 'Warekena',
    'curripaco' : 'Koripako',
    'tuiuca' : 'Tuyuka',
    'kubeo' : 'Kubeo',
    'korupaco' : 'Koripako',
    'kiripaco' : 'Koripako',
    '22.09.1988' : '?',
    'kaixiawa' : 'Kaixana',
    'valcileia pinto ramos' : '?',
    'cokama' : 'Kokama',
    'ticuna ' : 'Tikuna',
    'kaixana' : 'Kaixana',
    'muduruku' : 'Munduruku',
    'parintintin' : 'Parintintim',
    'munducuku' : 'Munduruku',
    'muncuruku' : 'Munduruku',
    'satere-mawe' : 'Sateré Mawé',
    '?' : '?',
    'escarianob' : 'Hixkaryana', 
    'excariano' : 'Hixkaryana',
    'escariano' : 'Hixkaryana',
    'escariana' : 'Hixkaryana',
    'hexcariano' : 'Hixkaryana',
    'apaurina' : 'Apurinã',
    'jamandi' : 'Jamamadi',
    'jamadi' : 'Jamamadi',
    'caixana' : 'Kaixana',
    'kanmari' : 'Kanamari',
    'arapaco' : 'Arapaso',
    'caxinaua' : 'Caxinauá',
    'mayurura' : 'Mayoruna',
    'macu' : 'Maku',
    'mayoruna' : 'Mayoruna',
    'maku yupy' : 'Maku',
    'rupida' : 'Hupda',
    'mayuryna' : 'Mayoruna',
    'wanana' : 'Wanana',
    'wanano' : 'Wanana', 
    'nadele' : '?',
    'maku' : 'Maku',
    'mayuruna' : 'Mayoruna',
    'mauyruna' : 'Mayoruna',
    'wexequena' : '?',
    'iauarete' : '?',
    'weewkema' : '?',
    'branca' : '?'
}

servicereceived_dict = {
    'usg de joelho' : 'exame',
	'laboratoriais' : 'exame',
	'mamografia' : 'exame',
	'usg mama' : 'exame',
	'laboratoriais e mielograma' : 'exame',
	'rx de torax' : 'exame',
	'laboratoriais' : 'exame',
	'eeg' : 'exame',
	'rnm crânio' : 'exame',
	'laboratoriais' : 'exame',
	'rx de torax' : 'exame',
	'ecg' : 'exame',
	'laboratoriais' : 'exame',
	'ecg' : 'exame',
	'rx torax' : 'exame',
	'litotripsia extracorporea' : 'procedimento cirúrgico',
	'ecg' : 'exame',
	'laboratoriais' : 'exame',
	'cirurgiao cabeca e pescoco' : 'procedimento cirúrgico',
	'eeg' : 'exame',
	'cirurgiao geral' : 'procedimento cirúrgico',
	'cirurgiao geral' : 'procedimento cirúrgico',
	'exames laboratoriais' : 'exame',
	'usg de abdome' : 'exame',
	'exame de panorâmico' : 'exame',
	'exames laboratoriais' : 'exame',
	'rnm' : 'exame',
	'rx de femur d' : 'exame',
	'cirurgiao vascular' : 'procedimento cirúrgico',
	'curativo' : 'curativo',
	'cirurgiao vascular' : 'procedimento cirúrgico',
	'cirurgiao vascular' : 'procedimento cirúrgico',
	'cirurgiao vascular' : 'procedimento cirúrgico',
	'rx ' : 'exame',
	'tc de abdômen superior e pelve.' : 'exame',
	'exames laboratoriais' : 'exame',
	'exame coleta de material – pele' : 'exame',
	'triagem' : '?',
	'exames laboratoriais' : 'exame',
	'exames laboratoriais' : 'exame',
	'clinica geral' : 'consulta',
	'exames laboratoriais ' : 'exame',
	'conizacao ' : 'procedimento cirúrgico',
	'curativo' : 'curativo',
	'internacao' : 'internação',
	'cirurgiao plastico' : 'procedimento cirúrgico',
	'exames laboratoriais/rx de torax' : 'exame',
	'tc de abdome e pelve' : 'exame',
	'ecocardiograma' : 'exame',
	'holter 24horas' : 'exame',
	'cirurgiao plastico' : 'procedimento cirúrgico',
	'curativo' : 'curativo',
	'rx ' : 'exame',
	'curativo' : 'curativo',
	'curativo' : 'curativo',
	'curativo' : 'curativo',
	'curativo' : 'curativo',
	'rnm de bacia/pelve' : 'exame',
	'clinico geral' : 'consulta',
	'cirurgiao geral' : 'consulta',
	'usg de abdome superior' : 'exame',
	'exames laboratoriais' : 'exame',
	'rx de torax' : 'exame',
	'cirurgiao geral' : 'consulta',
	'rx' : 'exame',
	'exames laboratoriais' : 'exame',
	'tc de torax' : 'exame',
	'tc de torax c/ contraste' : 'exame',
	'teste de baar' : 'exame',
	'cirurgiao toracico' : 'consulta',
	'clinico geral' : 'consulta',
	'medicacao injetavel de 12/12hs' : 'medicação',
	'exames laboratoriais + medicacao' : 'exame e medicação',
	'medicacao injetavel 1x ao dia' : 'medicação',
	'medicacao injetavel' : 'medicação',
	'exames laboratoriais ' : 'exame',
	'medicacao injetavel' : 'medicação',
	'medicacao injetavel' : 'medicação',
	'medicacao injetavel' : 'medicação',
	'medicacao injetavel' : 'medicação',
	'medicacao injetavel' : 'medicação',
	'exame de pele' : 'exame',
	'medicacao injetavel' : 'medicação',
	'medicacao injetavel' : 'medicação',
	'medicacao injetavel' : 'medicação',
	'medicacao injetavel' : 'medicação',
	'exames laboratoriais' : 'exame',
	'medicacao injetavel' : 'medicação',
	'exames laboratoriais' : 'exame',
	'medicacao injetavel' : 'medicação',
	'medicacao injetavel' : 'medicação',
	'medicacao injetavel' : 'medicação',
	'medicacao injetavel' : 'medicação',
	'medicacao injetavel' : 'medicação',
	'exames laboratoriais e medicacao' : 'exame e medicação',
	'exames laboratoriais e medicacao' : 'exame e medicação',
	'medicacao injetavel' : 'medicação',
	'medicacao injetavel' : 'medicação',
	'medicacao injetavel' : 'medicação',
	'medicacao injetavel' : 'medicação',
	'medicacao injetavel' : 'medicação',
	'cirurgiao geral' : 'consulta',
	'usg de abdômen/colangiorressonância' : 'exame',
	'exames laboratoriais' : 'exame',
	'rx, ecg' : 'exame',
	'cirurgiao geral' : 'consulta',
	'exame de ppd' : 'exame',
	'prova ventilatoria' : 'exame',
	'internacao' : 'internação',
	'cirurgiao buco maxilo' : 'consulta',
	'cirurgiao buco maxilo' : 'consulta',
	'tc de face' : 'exame',
	'exames laboratoriais' : 'exame',
	'ecg' : 'exame',
	'cirurgiao buco maxilo' : 'consulta',
	'exames laboratoriais, eas e epf' : 'exame',
	'biopsia' : 'procedimento cirúrgico',
	'exames laboratoriais' : 'exame',
	'rnm de crânio' : 'exame',
	'obstetra' : 'consulta',
	'quimioterapia' : 'tratamento',
	'teste de covid-19' : 'exame',
	'quimioterapia' : 'tratamento',
	'quimioterapia' : 'tratamento',
	'clinico geral' : 'consulta',
	'rnm de abdômen' : 'exame',
	'clinico geral' : 'consulta',
	'tc de torax e abdômen' : 'exame',
	'rx de torax' : 'exame',
	'radioterapia' : 'tratamento',
	'radioterapia' : 'tratamento',
	'radioterapia' : 'tratamento',
	'radioterapia' : 'tratamento',
	'radioterapia' : 'tratamento',
	'radioterapia' : 'tratamento',
	'radioterapia' : 'tratamento',
	'radioterapia' : 'tratamento',
	'clinico geral' : 'consulta',
	'radioterapia' : 'tratamento',
	'consulta de enfermagem ' : 'consulta',
	'usg do aparelho urinario' : 'exame',
	'exames laboratoriais' : 'exame',
	'psiquiatra' : 'consulta',
	'baar' : 'exame',
	'ppd' : 'exame',
	'beta hcg' : 'exame',
	'obstetra' : 'consulta',
	'exames laboratoriais, ppd, vacina' : 'exame',
	'leitura de ppd' : 'exame',
	'usg obstetrica' : 'exame',
	'obstetra' : 'consulta',
	'sorologia' : 'exame',
	'exames laboratoriais' : 'exame',
	'baciloscopia de pele' : 'exame',
	'exames laboratoriais, rx de torax, maos e punho.' : 'exame',
	'rnm de coluna lombar' : 'exame',
	'exames laboratoriaias' : 'exame',
	'exames laboratoriais' : 'exame',
	'rnm de crânio' : 'exame',
	'pccu' : 'exame',
	'usg transvaginal e beta hcg' : 'exame',
	'beta hcg quantitativo' : 'exame',
	'beta hcg quantitativo/epf/eas' : 'exame',
	'beta hcg quantitativo' : 'exame',
	'usg transvaginal e de abdome total' : 'exame',
	'beta hcg quantitativo' : 'exame',
	'beta hcg quantitativo/ exames laboratoriais' : 'exame',
	'beta hcg quantitativo' : 'exame',
	'rx de torax' : 'exame',
	'beta hcg quantitativo' : 'exame',
	'beta hcg quantitativo' : 'exame',
	'beta hcg quantitativo' : 'exame',
	'usg transvaginal' : 'exame',
	'cirurgia geral' : 'consulta',
	'conizacao' : 'procedimento cirúrgico',
	'clinico' : 'consulta',
	'clinico' : 'consulta',
	'clinico' : 'consulta',
	'exames laboratoriais' : 'exame',
	'usg de vias urinarias' : 'exame',
	'usg transvaginal' : 'exame',
	'usg com dopller venoso' : 'exame',
	'vascular' : 'consulta',
	'vascular' : 'consulta',
	'usg de regiao cervical' : 'exame',
	'exames laboratoriais' : 'exame',
	'enfermagem(triagem)' : '?',
	'exames laboratoriais e carga viral' : 'exame',
	'exame oftalmologico' : 'exame',
	'consulta c/ otorino' : 'consulta',
	'rx de coluna' : 'exame',
	'exames laboratoriais' : 'exame',
	'exame de urodinamico completo' : 'exame',
	'retinologo' : 'consulta',
	'laboratoriais' : 'exame',
	'laboratoriais' : 'exame',
	'laboratoriais' : 'exame',
	'usg obstetrica' : 'exame',
	'pre-natal' : 'consulta',
	'pre-natal' : 'consulta',
	'pre-natal' : 'consulta',
	'usg de abdome total' : 'exame',
	'internacao para eda' : 'exame',
	'usg de abdome total' : 'exame',
	'rx de joelho e coxa' : 'exame',
	'realizou exames laboratoriais e rx de torax + vacinas crie' : 'exame',
	'realizou coleta de exame preventivo' : 'exame',
	'realizou usg transvaginal, tireoide e abdome total ' : 'exame',
	'enfermagem(triagem)' : '?',
	'obstetra' : 'consulta',
	'obstetra' : 'consulta',
	'obstetra' : 'consulta',
	'exames laboratoriais' : 'exame',
	'exames laboratoriais' : 'exame',
	'exame baar' : 'exame',
	'prova ventilatoria' : 'exame',
	'realizou exames laboratoriais' : 'exame',
	'realizou rx de torax ' : 'exame',
	'clinico geral' : 'consulta',
	'clinico geral' : 'consulta',
	'clinico geral' : 'consulta',
	'obstetra' : 'consulta',
	'clinica medica' : 'consulta',
	'exames laboratoriais' : 'exame',
	'clinico geral' : 'consulta',
	'exame de trm(escarro)' : 'exame',
	'rx de torax' : 'exame',
	'clinico geral ' : 'consulta',
	'rx de torax' : 'exame',
	'internacao' : 'internação',
	'exame baar' : 'exame',
	'exame de bcr' : 'exame',
	'curativos' : 'curativo',
	'exames laboratoriais' : 'exame',
	'curativos' : 'curativo',
	'rx de torax' : 'exame',
	'eas, epf, exames laboratoriais, usg de abdômen.' : 'exame',
	'exames laboratoriais' : 'exame',
	'eda' : 'exame',
	'rnm de vias biliares' : 'exame',
	'exames laboratoriais, usg de tireoide, ecg, eco.' : 'exame',
	'mapa' : 'exame',
	'retirada de mapa' : 'exame',
	'holter' : 'exame',
	'retirada de holter' : 'exame',
	'paaf' : 'exame',
	'ex. sorologia, ex. laboratoriais' : 'exame',
	'exames laboratoriais' : 'exame',
	'rnm de abdômen total' : 'exame',
	'eda' : 'exame',
	'hmg completo,epf ' : 'exame',
	'eas ' : 'exame',
	'enfermeira ' : '?',
	'cirurgia-retirada de melanoma nodular ' : 'procedimento cirúrgico',
	'exames laboratoriais' : 'exame',
	'quimioterapia ' : 'tratamento',
	'exame de audiometria' : 'exame',
	'exames laboratoriais' : 'exame',
	'exame de raio x' : 'exame',
	'tc de torax ' : 'exame',
	'usg de abdome total ' : 'exame',
	'ecott ' : 'exame',
	'mamografia ' : 'exame',
	'biopsia de mama' : 'procedimento cirúrgico',
	'setor de hepatites' : '?',
	'exame de carga viral de hepatite' : 'exame',
	'sorologia' : 'exame',
	'exames de bioquimica' : 'exame',
	'prova de funcao pulmonar completa' : 'exame',
	'carga viral da hepatite b e exames laboratoriais' : 'exame',
	'ultrassom com doppler' : 'exame',
	'raio x de torax' : 'exame',
	'eletrocardiograma' : 'exame',
	'exames laboratoriais' : 'exame',
	'exames laboratoriais e sorologia' : 'exame',
	'rx de torax e bacia' : 'exame',
	'exames laboratoriais' : 'exame',
	'exames laboratoriais' : 'exame',
	'tc de crânio' : 'exame',
	'exames laboratoriais' : 'exame',
	'usg com doppler' : 'exame',
	'consulta por tfd ' : 'exame',
	'ecocardiograma' : 'exame',
	'psiquiatrico' : 'consulta',
	'psiquiatrico' : 'consulta',
	'rnm de crânio' : 'exame',
	'psiquiatrico' : 'consulta',
	'usg de abdomen superior ' : 'exame',
	'ecg ' : 'exame',
	'exames laboratoriais ' : 'exame',
	'rnm de coluna lombo-sacra ' : 'exame',
	'rx de antebraco' : 'exame',
	'ecocardiograma' : 'exame',
	'triagem' : '?',
	'exames laboratoriais' : 'exame',
	'ultrassonografia de mamas' : 'exame',
	'rx de torax' : 'exame',
	'exames laboratoriais' : 'exame',
	'usg transvaginal + usg abdominal' : 'exame',
	'densitometria ossea' : 'exame',
	'usg transvaginal' : 'exame',
	'tc de crânio' : 'exame',
	'hemograma' : 'exame',
	'urocultura' : 'exame',
	' usg de abdome total' : 'exame',
	'covid-19' : 'exame',
	'ultrassonografia de tireoide' : 'exame',
	'tc de abdômen' : 'exame',
	'exames laboratoriais' : 'exame',
	'avaliacao transplante figado' : 'consulta',
	'exames laboratoriais' : 'exame',
	'ressonância magnetica ' : 'exame',
	'medico da radioterapia ' : 'consulta',
	'exame de beta hcg quantitativo ' : 'exame',
	'medico da radioterapia ' : 'consulta',
	'exames laboratoriais ' : 'exame',
	'medico da quimioterapia ' : 'consulta',
	'exames laboratoriais ' : 'exame',
	'medico da radioterapia ' : 'consulta',
	'medico da radioterapia ' : 'consulta',
	'exames laboratoriais' : 'exame',
	'1ª sessao de pulsoterapia' : 'tratamento',
	'2ª sessao de pulsoterapia' : 'tratamento',
	'exames laboratoriais carga viral' : 'exame',
	'beta hcg' : 'exame',
	'raio x de coluna cervical' : 'exame',
	'ultrassonografia de rins e prostata' : 'exame',
	'teste do covid-19' : 'exame',
	'exame de raio x' : 'exame',
	'exame de raio x' : 'exame',
	'tomografia computadorizada de torax' : 'exame',
	'medica da dor' : 'consulta',
	'cirurgiao toracico' : 'consulta',
	'exames laboratoriais' : 'exame',
	'exame de raio x de torax' : 'exame',
	'eletrocardiograma' : 'exame',
	'tomografia computadorizada de torax, abdômen superior e pelve.' : 'exame',
	'2ª parte com contraste dos exames de tomografia computadorizada de torax, abdômen superior e pelve.' : 'exame',
	'exames laboratoriais' : 'exame',
	'rx de bacia' : 'exame',
	'exames laboratoriais' : 'exame',
	'ressonância magnetica de crânio' : 'exame',
	'exames laboratoriais ' : 'exame',
	'exames laboratoriais' : 'exame',
	'exames laboratoriais' : 'exame',
	'exames laboratoriais' : 'exame',
	'exames laboratoriais, eas e proteinuria de 24 horas' : 'exame',
	'exame de albumina serica e combo direto' : 'exame',
	'consulta de pre natal' : 'consulta',
	'ecocardiografia fetal' : 'exame',
	'consulta de pre natal' : 'consulta',
	'exames laboratoriais' : 'exame',
	'gota espessa' : '?',
	'ultrassonografia morfologica' : 'exame',
	'estudo urodinamico' : 'exame',
	'rnm de pelve' : 'exame',
	'ecocardiograma com doppler' : 'exame',
	'exames laboratoriais' : 'exame',
	'exames laboratoriais' : 'exame',
	'exames laboratoriais' : 'exame',
	'raio x de torax' : 'exame',
	'exames laboratoriais' : 'exame',
	'oncologia' : 'consulta',
	'exames laboratoriais' : 'exame',
	'oncologia' : 'consulta',
	'exames laboratoriais' : 'exame',
	'oncologia' : 'consulta',
	'exames laboratoriais' : 'exame',
	'enf. binda' : '?',
	'exames laboratoriais' : 'exame',
	'oncologia' : 'consulta',
	'exames laboratoriais' : 'exame',
	'oncologia' : 'consulta',
	'raio x de torax' : 'exame',
	'biopsia' : 'procedimento cirúrgico',
	'ultrassonografia de mama' : 'exame',
	'toxoplasmose(igm/igg)' : 'exame',
	'servico de hepatites.' : 'exame',
	'otorrinolaringologia' : 'consulta',
	'dermatologia' : 'consulta',
	'hemograma completo e bioquimicos' : 'exame',
	'dermatologia' : 'consulta',
	'buco-maxilo' : '?',
	'clonixinato de lisina 125 mg + cloridrato de ciclobenzaprina 5 mg' : '?',
	'patricia jane' : '?',
	'exames de: carga viral, exames laboratoriais, beta hcg e eas' : 'exame',
	'exame de eletrocardiograma' : 'exame',
	'exame de ecocardiograma' : 'exame',
	'exames laboratorias' : 'exame',
	'usg abdome total' : 'exame',
	'ecg' : 'exame',
	'cirurgiao deral' : 'consulta',
	'ressonância magnetica de abdome e pelve' : 'exame',
	'exames laboratoriais ' : 'exame',
	'eletrocardiograma ' : 'exame',
	'raio x de torax ' : 'exame',
	'raio x de torax ' : 'exame',
	'xenodiagnostico ' : 'exame',
	'procedimento cirurgico de pterigio em olho direito' : 'procedimento cirúrgico',
	'rnm de abdome superior ' : 'exame',
	'exames laboratoriais ' : 'exame',
	'exames de: sorologia, xenodiagnostico e eletrocardiograma.' : 'exame',
	'ecocardiograma' : 'exame',
	'realizou ecg  ' : 'exame',
	'realizou rx de torax  ' : 'exame',
	'realizou exames laboratoriais  ' : 'exame',
	'cirurgiao oncologico' : 'consulta',
	'exame de ultrassonografia' : 'exame',
	'exames laboratoriais' : 'exame',
	'exames laboratoriais' : 'exame',
	'tomografia computadorizada' : 'exame',
	'exames laboratoriais' : 'exame',
	'exames laboratoriais' : 'exame',
	'medica da quimioterapia' : 'exame',
	'exames laboratoriais, eas e proteinuria de 24 horas.' : 'exame',
	'raio x de torax' : 'exame',
	'exames laboratoriais' : 'exame',
	'exames laboratoriais' : 'exame',
	'pesquisa de baar ' : 'exame',
	'cultura' : 'exame',
	'raio x de torax ap/perfil' : 'exame',
	'exames laboratoriais' : 'exame',
	'exame de raio x de torax' : 'exame',
	'exame de eletrocardiograma' : 'exame',
	'ultrassonografia de prostata, abdome total.' : 'exame',
	'teste de covid- 19' : 'exame',
	'rm de pelve abdome superior' : 'exame',
	'tc’s de face, torax e pescoco  hufm' : 'exame',
	'realizou rx de clavicula' : 'exame',
	'realizou tc de crânio' : 'exame',
	'hemograma + usg de abdômen+ rx de torax  ' : 'exame',
	'rx de torax ' : 'exame',
	'realizou exames laboratoriais' : 'exame',
	'realizou  laboratoriais ecg ' : 'exame',
	'exames laboratoriais' : 'exame',
	'tc de abdome ' : 'exame',
	'realizou exame laboratoriais ' : 'exame',
	'realizou rx ' : 'exame',
	'realizou exame de laboratoriais' : 'exame',
	'realizou exame laboratoriais ' : 'exame',
	'rx de torax ' : 'exame',
	'realizou ecg' : 'exame',
	'rx de mao' : 'exame',
	'exame laboratoriais ' : 'exame',
	'exame rnm vias biliares' : 'exame',
	'realizou rx de torax ' : 'exame',
	'realizou usg do aparelho urinario ' : 'exame',
	'realizou usg abdômen e transvaginal' : 'exame',
	'realizou exame laboratoriais' : 'exame',
	'eletroencefalograma' : 'exame',
	'realizou exame laboratoriais' : 'exame',
	'realizou rx do torax ' : 'exame',
	'realizou ecg' : 'exame',
	'exames laboratoriais' : 'exame',
	'raio-x de torax' : 'exame',
	'usg de abdome total' : 'exame',
	'mamografia bilateral' : 'exame',
	'exames laboratoriais ' : 'exame',
	'exames laboratoriais ' : 'exame',
	'exames laboratoriais ' : 'exame',
	'exames laboratoriais ' : 'exame',
	'raio-x de torax' : 'exame',
	'exames laboratoriais ' : 'exame',
	'ecg + risco cirurgico' : 'exame',
	'tgo-tgp-gama gt- fosfastase- alcalina-bilirrubina.' : 'exame',
	'exames laboratoriais  ' : 'exame',
	'usg obstetrica  ' : 'exame',
	'usg abdome superior ' : 'exame',
	'tonometria' : 'exame',
	'usg globo ocular' : 'exame',
	'exames laboratoriais ' : 'exame',
	'raio-x de torax pa/p' : 'exame',
	'eletrocardiograma ' : 'exame',
	'parecer de risco cirurgico ' : 'exame',
	'usg de abdome total' : 'exame',
	'tc de abdome' : 'exame',
	'endoscopia digestiva com biopsia' : 'exame',
	'hcv, hb e vdrl' : 'exame',
	'hiv' : 'exame',
	'usg de abdome' : 'exame',
	'ressonancia de abdome' : 'exame',
	'eda' : 'exame',
	'exames laboratoriais ' : 'exame',
	'eletrocardiograma' : 'exame',
	'raio-x de torax' : 'exame',
	'parecer de risco cirurgico ' : 'exame',
	'usg de globo ocular' : 'exame',
	'biomicroscopia de fundo de olho' : 'exame',
	'destro de 231 mg/dl,' : 'exame',
	'cea- aff, bhq' : 'exame',
	'atendido em carater de urgencia' : 'urgência',
	'urgencia/ internacao' : 'urgência',
	'bhcg quantitativo' : 'exame',
	'atendida em carater de urgencia pelo obstetra' : 'consulta',
	'hemograma, tgo, tgp.' : 'exame',
	'urgencia/internado' : 'urgência',
	'realizou exames laboratoriais ' : 'exame',
	'urgencia/ intenacao ' : 'urgência',
	'exames laboratoriais' : 'exame',
	'hemograma' : 'exame',
	'usg de vias urinarias' : 'exame',
	'psa, eas, cultura.' : 'exame',
	'usg aparelho urinario' : 'exame',
	' foi atendido pela' : '?',
	'foi avaliado pela clinico geral' : 'consulta',
	'xenodiagnostico' : 'exame',
	'urgencia/internacao ' : 'urgência',
	'internacao ' : 'internação',
	'realizou curativo ' : 'curativo',
	'cirurgiao vascular ' : 'consulta',
	'realizou eco' : 'exame',
	'realizou exames laboratoriais' : 'exame',
	'realizou usg de abdome' : 'exame',
	'realizou endoscopia digestiva' : 'exame',
	'realizou tc de abdome total' : 'exame',
	' realizou exames laboratoriais' : 'exame',
	'realizou consulta ' : 'consulta',
	'retorno' : 'consulta',
	'atendido pela ' : '?',
	'foi avaliado em carater de urgencia' : 'consulta',
	'realizou consulta com psiquiatra' : 'consulta',
	'realizou consulta ' : 'consulta',
	'realizou consulta com psiquiatra' : 'consulta',
	'consulta em carater de urgencia' : 'consulta',
	'carga viral hepatite b, hemograma completo bioquimico, eas+epf.' : 'exame',
	'usg de abdome' : 'exame',
	'coleta de material para biopsia' : 'procedimento cirúrgico',
	'entregue material para biopsia' : 'procedimento cirúrgico',
	'raio-x de torax' : 'exame',
	'exames laboratoriais ' : 'exame',
	'exames laboratoriais ' : 'exame',
	'ecg e risco cirurgico ' : 'exame',
	'realizou exame de sangue.' : 'exame',
	'realizou raio-x do joelho' : 'exame',
	'realizou exame laboratoriais ' : 'exame',
	'realizou eda com coleta de biopsia' : 'exame e procedimento cirúrgico',
	'exame de refracao ocular oe' : 'exame',
	'realizou exames hemograma completo ' : 'exame',
	'realizou exame de ecg' : 'exame',
	'realizou tc de torax ' : 'exame',
	'realizou exames laboratoriais' : 'exame',
	'realizou triagem dermatologica ' : 'exame',
	'realizou rnm de bacia e pelvica' : 'exame',
	'realizou exames laboratoriais.' : 'exame',
	'realizou biopsia / com resultados pendentes' : 'procedimento cirúrgico',
	'realizou exames laboratoriais' : 'exame',
	'realizou radioterapia' : 'tratamento',
	'realizou preventivo' : 'exame',
	'realizar procedimento cirurgico (herniorrafia)' : 'procedimento cirúrgico',
	'realizou consulta oncologico ' : 'consulta',
	'exames laboratoriais' : 'exame',
	'realizou sangria terapeutica' : 'tratamento',
	'realizou laboratoriais e sorologias  ' : 'exame',
	'realizou usg de abdome total' : 'exame',
	'realizou raio x de torax ' : 'exame',
	'realizou exames laboratoriais ' : 'exame',
	'realizou ecg' : 'exame',
	'neurocirurgiao' : 'consulta',
	'exames laboratoriais' : 'exame',
	'usg prostata' : 'exame',
	'sorologias ' : 'exame',
	'urgencia /internacao' : 'urgência',
	'urgencia /internacao' : 'urgência',
	'urgencia /internacao' : 'urgência',
	'exames laboratoriais' : 'urgência',
	'usg transretal prostata' : 'exame',
	'urologia' : 'consulta',
	'urgencia/internacao' : 'urgência',
	'pos-operatorio' : 'consulta',
	'pos-operatorio' : 'consulta',
	'tomografia computorizada de abdome' : 'exame',
	'realizou laboratoriais, usg de abdômen  ' : 'exame',
	'realizou rx de crânio ' : 'exame',
	'realizou rnm de coluna' : 'exame',
	'realizou exame laboratoriais ' : 'exame',
	'realizou exame de rx' : 'exame',
	'realizou procedimentos cirurgico biopsia' : 'procedimento cirúrgico',
	'realizou coleta de biopsia' : 'procedimento cirúrgico',
	'rnm de crânio' : 'exame',
	'realizou refracao do olho d' : 'exame',
	'realizou exame topografia' : 'exame',
	'realizou usg' : 'exame',
	'realizou exame laboratoriais ' : 'exame',
	'realizou exame laboratoriais' : 'exame',
	'realizou usg do abdômen superior ' : 'exame',
	'realizou usg transvaginal' : 'exame',
	'realizou mamografia (particular)' : 'exame',
	'exames laboratoriais' : 'exame',
	'rnm de bacia e pelve' : 'exame',
	'exame densitometria ossea' : 'exame',
	'raio-x de joelho d/e' : 'exame',
	'exames laboratoriais ' : 'exame',
	'usg de cotovelo direito ' : 'exame',
	'exames laboratoriais ' : 'exame',
	'raio-x de torax' : 'exame',
	'exames laboratoriais' : 'exame',
	'tomografia computadorizada de pelve e abdome superior' : 'exame',
	'raio-x de mao direita' : 'exame',
	'realizou exames laboratoriais ' : 'exame',
	'realizou exames laboratoriais' : 'exame',
	'urgencia /intencao' : 'urgência',
	'usg de prostata' : 'exame',
	'hemograma, ureia, creatinina, glicemia, eas psa total' : 'exame',
	'consulta carater de urgencia para, avaliado pelo' : 'consulta',
	'hemograma completo e ' : 'exame',
	'beta hcg' : 'exame',
	'realizou rx de torax ' : 'exame',
	'realizou tc de pescoco, laringe, tireoide, crânio. ' : 'exame',
	'realizou exames laboratoriais ' : 'exame',
	'realizou ecg' : 'exame',
	'realizou cirurgia ' : 'procedimento cirúrgico',
	'cirurgiao cabeca e pescoco' : 'consulta',
	'cirurgiao cabeca e pescoco' : 'consulta',
	'cirurgiao plastico' : 'consulta',
	'realizou exames laboratoriais ' : 'exame',
	'realizou usg de prostata ' : 'exame',
	'realizou exames laboratoriais ' : 'exame',
	'realizou usg de mama' : 'exame',
	'tc de torax' : 'exame',
	'exames laboratoriais' : 'exame',
	'realizou exame de eco b' : 'exame',
	'realizou exames pre-operatorios' : 'exame',
	'avaliacao urgencia oftalmologia' : 'consulta',
	'oftalmologia' : 'consulta',
	'tc de crânio' : 'exame',
	'rx' : 'exame',
	'consulta em carater de urgencia com neurocirurgiao ' : 'consulta',
	'realizou exame eco b ' : 'exame',
	'rm' : 'exame',
	'raio x de torax' : 'exame',
	'ppd' : 'exame',
	'tc de torax' : 'exame',
	'realizado exame de ecocardiograma' : 'exame',
	'realizou fisioterapia' : 'tratamento não medicamentoso',
	'realizou exames de sorologias' : 'exame',
	'realizou o rx de torax' : 'exame',
	'realizou preventivo e usg transvaginal' : 'exame',
	'realizou consulta ' : 'consulta',
	'realizou consulta' : 'consulta',
	'realizou consulta' : 'consulta',
	'realizou consulta com psiquiatra' : 'consulta',
	'exames laboratoriais+eletrocardiograma' : 'exame',
	'teste ergometrico' : 'exame',
	'usg de abdome total, ecocardiograma e mapa' : 'exame',
	'pi prevencao de incapacidade e baar-baciloscopia' : 'exame',
	'endoscopia digestiva alta-eda com biopsia' : 'procedimento cirúrgico',
	'eletrocardiograma' : 'exame',
	'parecer de risco cirurgico ' : 'exame',
	'realizou exame oftalmologico ' : 'exame',
	'realizou anti-hiv -1 , hiv 2' : 'exame',
	'realizou colostomia e biopsia' : 'exame',
	'realizou exame de raio – x' : 'exame',
	'exame laboratoriais' : 'exame',
	'realizou raio-x de torax, hemograma e ecg ' : 'exame',
	'realizou procedimento cirurgico traqueostomia' : 'exame',
	'realizou pccu' : 'exame',
	'realizou exame de colposcopia' : 'exame',
	'raio-x' : 'exame',
	'exames laboratoriais ' : 'exame',
	'realizou conizacao ' : 'procedimento cirúrgico',
	'realizado eeg ' : 'exame',
	'realizou exame audiometria, imitanciometria, eoa e bera' : 'exame',
	'consulta para avaliacao auditiva ' : 'consulta',
	'realizou procedimento cirurgico ' : 'procedimento cirúrgico',
	'realizou exames laboratoriais ' : 'exame',
	'urgencia/internacao' : 'urgência',
	'consulta cirurgiao cabeca e pescoco' : 'consulta',
	'tc de pescoco ' : 'exame',
	'raio-x de ombro' : 'exame',
	'usg de ombro' : 'exame',
	'raio-x de torax' : 'exame',
	'exames laboratoriais' : 'exame',
	'eletrocardiograma ' : 'exame',
	'ecg' : 'exame',
	'raio-x' : 'exame',
	'exame de ultrassonografia de mama' : 'exame',
	'exame de mamografia' : 'exame',
	'core biopsia ' : 'procedimento cirúrgico',
	'realizou exame ' : 'exame',
	'realizou tc de abome superior' : 'exame',
	'realizou ecg ' : 'exame',
	'realizar laboratoriais ' : 'exame',
	'realizou laboratoriais ' : 'exame',
	'realizou exame ' : 'exame',
	'usg transvaginal' : 'exame',
	'consulta' : 'consulta',
	'consulta' : 'consulta',
	'realizou usg abdômen ' : 'exame',
	'ressonância magnetica de coluna' : 'exame',
	'tomografia computadorizada de crânio' : 'exame',
	'anti-hiv –vdrl – hcv – hbsag. ' : 'exame',
	'realizou biopsia de pele que foi coletado pela drª kamila.' : 'procedimento cirúrgico',
	'raio-x de torax' : 'exame',
	'exames laboratoriais' : 'exame',
	'eletrocardiograma ' : 'exame',
	'ecocardiograma' : 'exame',
	'eletrocardiograma' : 'exame',
	'parecer de risco cirurgico ' : 'exame',
	'internacao para procedimento cirurgico de colecistectomia' : 'procedimento cirúrgico',
	'campimetria' : 'exame',
	'gonioscopia, bio de fo, ctd' : 'exame',
	'raio-x de coluna toracica e bacia' : 'exame',
	'exames laboratoriais' : 'exame',
	'realizou exames laboratoriais' : 'exame',
	'eas, hemograma completo, vdrl.' : 'exame',
	'exames laboratoriais' : 'exame',
	'raio x de torax' : 'exame',
	'otorrino' : 'consulta',
	'usg transvaginal ' : 'exame',
	'cirurgia de mioma' : 'procedimento cirúrgico',
	'avaliacao pos- operatorio ' : 'consulta',
	'urgencia ' : 'urgência',
	'usg + exames laboratoriais ' : 'exame',
	'urgencia obstetra' : 'urgência',
	'urgencia obstetra' : 'urgência',
	'urgencia obstetra' : 'urgência',
	'dr. guilherme' : '?',
	'imitoncimetria' : 'exame',
	'servico social ' : '?',
	'realizou sessões de fisioterapia ' : 'tratamento não medicamentoso',
	'neurologia ( urgencia )' : 'urgência',
	'neurologia (urgencia ) ' : 'urgência',
	'ppd' : 'exame',
	'sorologia' : 'exame',
	'rx de punho' : 'exame',
	'exame de usg transvaginal' : 'exame',
	'realizou usg de partes moles, punho d e e mao d e e pe d e e' : 'exame',
	'realizou exame de mamografia' : 'exame',
	'realizou audiometria' : 'exame',
	'foi atendida pela' : '?',
	'realizou exames laboratoriais' : 'exame',
	'realizou exame ecg' : 'exame',
	'realizou raio-x de coluna lombar' : 'exame',
	'realizou exames tc de abdome e eas' : 'exame',
	'rx de tornozelo' : 'exame',
	'realizou rnm' : 'exame',
	'realizou mamografia ' : 'exame',
	'tc de cranio' : 'exame',
	'exame de rnm' : 'exame',
	'realizou tc de face' : 'exame',
	'realizou exame de baar' : 'exame',
	'realizou exames laboratoriais ' : 'exame',
	'consulta cirurgiao de cabeca e pescoco' : 'consulta',
	'tomografia de crânio ' : 'exame',
	'exames laboratoriais e ecg' : 'exame',
	'ultrassonografia de abdome total ' : 'exame',
	'tomografia de crânio, exames laboratoriais ' : 'exame',
	'tomografia de crânio ' : 'exame',
	'exames laboratoriais ' : 'exame',
	'ecografico ' : 'exame',
	'exames laboratoriais ' : 'exame',
	'cirurgia de histerectomia' : 'procedimento cirúrgico',
	'encaminhada à urgencia' : 'urgência',
	'psa total e eas' : 'exame',
	'usg de prostata' : 'exame',
	'exames laboratoriais' : 'exame',
	'usg de vias urinaria' : 'exame',
	'usg de prostata' : 'exame',
	'realizou consulta com cirurgiao geral ' : 'consulta',
	'realizou consulta urgencia' : 'consulta',
	'rnm de coluna dorsal' : 'exame',
	'rnm de coluna lombar' : 'exame',
	'foi avaliado pelo ' : '?',
	'exame laboratorial' : 'exame',
	'realizou consulta com neurocirurgiao' : 'consulta',
	'realizou exame de psa total e eas' : 'exame',
	'eas' : 'exame',
	'realizou usg de prostata' : 'exame',
	'realizou exames laboratoriais' : 'exame',
	'realizou exame de usg' : 'exame',
	'realizou consulta com ' : 'consulta',
	'realizou consulta residente' : 'consulta',
	'realizou exames laboratoriais ' : 'exame',
	'realizou ecocardiograma ' : 'exame',
	'exames laboratoriais ' : 'exame',
	'exames laboratoriais ' : 'exame',
	'exame de eas ' : 'exame',
	'hemograma completo tgo-tgp e bioquimica ' : 'exame',
	'endoscopia digestiva alta. ' : 'exame',
	'exames laboratoriais ' : 'exame',
	'ultrassonografia de abdome total com doppler. ' : 'exame',
	'endoscopia digestiva alta. ' : 'exame',
	'ultrassonografia de abdome. ' : 'exame',
	'carga viral da hepatite b, hemograma completo bioquimico. ' : 'exame',
	'usg abdominal' : 'exame',
	'exames de sangue ' : 'exame',
	'rnm de crânio' : 'exame',
	'exames laboratoriais' : 'exame',
	'realizou raio x' : 'exame',
	'exame laboratoriais' : 'exame',
	'realizou eeg' : 'exame',
	'realizou rnm de crânio ' : 'exame',
	'realizou usg de abdome' : 'exame',
	'exames laboratoriais' : 'exame',
	'exames laboratoriais + raio x de torax ' : 'exame',
	'realizou ecg' : 'exame',
	'realizou usg com dopller' : 'exame',
	'exames laboratoriais' : 'exame',
	'realizou usg transvaginal ' : 'exame',
	'usg bolsa escrotal' : 'exame',
	'usg abdome total' : 'exame',
	'tc de abdome' : 'exame',
	'rx de torax' : 'exame',
	'exame de tomografia computadorizada de crânio' : 'exame',
	'ultrassonografia de prostata' : 'exame',
	'ressonância magnetica de pelve' : 'exame',
	'carga viral hepatite b, bioquimica, eas+epf.' : 'exame',
	'ultrassonografia' : 'exame',
	'exames laboratoriais e teste rapido' : 'exame',
	'tc de torax' : 'exame',
	'realizou consulta com dr. wornei' : 'consulta',
	'realizou usg vias urinarias' : 'exame',
	'realizou exames laboratorias' : 'exame',
	'exame realizado audiometria' : 'exame',
	'tc de mastoide' : 'exame',
	'rnm de crânio' : 'exame',
	'tc de crânio' : 'exame',
	'exame  realizado audiometria' : 'exame',
	'tc de mastoide' : 'exame',
	'rnm de crânio ' : 'exame',
	'cintilografia' : 'exame',
	'cintilografia' : 'exame',
	'tomografia de crânio' : 'exame',
	'exame de fan- anticorpos e anti-nucleo.' : 'exame',
	'tc de torax ' : 'exame',
	'baciloscopia' : 'exame',
	'usg de prostata e abdome total ' : 'exame',
	'rx de torax ' : 'exame',
	'raio-x de joelho e e d' : 'exame',
	'exames laboratoriais' : 'exame',
	'exames laboratoriais' : 'exame',
	'exame de eas' : 'exame',
	'hemograma completo tgo-tgp e bioquimica' : 'exame',
	'endoscopia digestiva alta.' : 'exame',
	'exames laboratoriais' : 'exame',
	'ultrassonografia de abdome total com doppler.' : 'exame',
	'endoscopia digestiva alta.' : 'exame',
	'ultrassonografia de abdome.' : 'exame',
	'carga viral da hepatite b, hemograma completo bioquimico.' : 'exame',
	'usg abdominal ' : 'exame',
	'exames de sangue' : 'exame',
	'rnm de coluna cervical' : 'exame',
	'atendimento em carater de urgencia ' : 'urgência',
	'atendimento em carater de urgencia' : 'urgência',
	'realizou usg transvaginal' : 'exame',
	'foi avaliada pelo clinico geral' : 'consulta',
	'consulta' : 'consulta',
	'consulta de urgencia' : 'consulta',
	'realizou consulta ' : 'consulta',
	'realizou raio-x torax ' : 'exame',
	'realizou exame laboratoriais' : 'exame',
	'realizou exame ecg' : 'exame',
	'realizou usg de prostata' : 'exame',
	'realizou ecg' : 'exame',
	'realizou raio   x de torax' : 'exame',
	'realizou exames laboratoriais' : 'exame',
	'realizou consulta com cirurgiao' : 'exame',
	'realizou consulta clinico geral' : 'consulta',
	'raio x torax e hmg completo' : 'exame',
	'urgencia' : 'urgência',
	'hemograma, bioquimica, glicemia, tgo +tgp' : 'exame',
	'sorologia' : 'exame',
	'exames laboratoriais' : 'exame',
	'tc bacia/pelve' : 'exame',
	'usgs torax, pelve e abdome' : 'exame',
	'raio x torax' : 'exame',
	'urgencia' : 'urgência',
	'cirurgiao' : 'consulta',
	'cirurgiao' : 'consulta',
	'exames laboratoriais' : 'exame',
	'exames laboratoriais' : 'exame',
	'raio x torax' : 'exame',
	'ecg' : 'exame',
	'realizou avaliacao de rx de face' : 'exame',
	'realizou usg  transvaginal' : 'exame',
	'raio x de torax ' : 'exame',
	'realizou ecg' : 'exame',
	'exames laboratoriais ' : 'exame',
	'exame eas' : 'exame',
	'realizou usg transvaginal' : 'exame',
	'teste rapido para hiv 1 e 2, vdrl' : 'exame',
	'tc de torax' : 'exame',
	'exames laboratoriais' : 'exame',
	'baar e ppd ' : 'exame',
	'tc de abdome e pelve' : 'exame',
	'hemograma' : 'exame',
	'qt ' : 'tratamento',
	'exames laboratoriais' : 'exame',
	'realizou o exame de ecocardiograma' : 'exame',
	'exames laboratoriais' : 'exame',
	'realizou tc de abdome superior pelve bacia e pescoco' : 'exame',
	'mi realizado exame de tcs' : 'exame',
	'foi avaliado pelo cirurgiao geral' : 'consulta',
	'foi avaliado pela medica ' : 'consulta',
	'foi atendido ' : '?',
	'atendido pela ' : '?',
	'internacao /cirurgia ' : 'procedimento cirúrgico',
	'curativo ' : 'curativo',
	'foi avaliada em carater de urgencia ' : 'urgência',
	'consulta de pos-operatorio ' : 'consulta',
	'foi avaliado pela buco maxilo' : 'consulta',
	'realizou exame rx' : 'exame',
	'realizou consulta  ' : 'consulta',
	'carga viral de hepatite b, pcr de delta, hemograma completo, bioquimica tgo+tgp, eas+epf.' : 'exame',
	'exame de ultrassonografia de abdome superior' : 'exame',
	'realizou exame laboratoriais' : 'exame',
	'realizou exame laboratoriais ' : 'exame',
	'exames laboratoriais' : 'exame',
	'cirurgiao geral' : 'consulta',
	'cirurgiao geral' : 'consulta',
	'cirurgiao geral' : 'consulta',
	'rm de pelve' : 'exame',
	'carga viral, hemograma completo.' : 'exame',
	'eas e epf' : 'exame',
	'eda c/ biopsia' : 'procedimento cirúrgico',
	'raio x' : 'exame',
	'exames laboratoriais' : 'exame',
	'ecg + risco cirurgico' : 'exame',
	'exames laboratoriais ' : 'exame',
	'tx hepatico com dr. tarcisio.' : 'exame',
	'realizou retirada de ponto do local da cirurgia ' : 'procedimento de remoção dos fios cirúrgicos',
	'realizou usg de abdômen ' : 'exame',
	'exames laboratoriais' : 'exame',
	'exames laboratoriais' : 'exame',
	'clearance de creatinina, proteinuria de 24h' : 'exame',
	'usg de prostata' : 'exame',
	'raio-torax, hemograma completo' : 'exame',
	'hemograma completo' : 'exame',
	'tomografia do torax' : 'exame',
	'endoscopia digestiva alta' : 'exame',
	'exames laboratoriais' : 'exame',
	'usg de abdome superior' : 'exame',
	'continuidade em seu tratamento de tfd' : '?',
	'realizou exames laboratoriais' : 'exame',
	'realizou consulta as' : 'consulta',
	'atendido pelo ortopedista' : 'consulta',
	'realizou consulta com dra. socorro sampaio hematologista' : 'consulta',
	'atendido pelo hematologista' : 'consulta',
	'atendido pelo hematologista' : 'consulta',
	'realizou consulta com o ginecologista' : 'consulta',
	'foi atendida pelo infectologista' : 'consulta',
	'realizou consulta dra. socorro sampaio hematologista' : 'consulta',
	'realizado consulta com cardiologista pediatra  ' : 'consulta',
	'realizou consulta infectologista pediatra' : 'consulta',
	'realizou consulta com dr° erik, neurologista ' : 'consulta',
	'realizou consulta com drº elson' : 'consulta',
	'atendida pelo ginecologista' : 'consulta',
	'avaliado pelo ortopedista' : 'consulta',
	'atendido em carater de urgencia pelo ortopedista' : 'consulta',
	'foi atendido pelo nefrologista em carater de urgencia ' : 'urgência',
	'foi atendido pela nefrologista' : 'consulta',
	'realizado consulta com urologista ' : 'consulta',
	'realizado consulta com nefrologista ' : 'consulta',
	'realizado avaliacao com infectologista ' : 'consulta',
	'realizou consulta hematologista' : 'consulta',
	'realizou consulta com gastroenterologista' : 'consulta',
	'realizou consulta com a hepatologista' : 'consulta',
	'foi atendido pelo dr. vinicius urologista' : 'consulta',
	'atendido em carater de urgencia com ortopedista' : 'urgência',
	'realizou consulta com neurologista pediatra' : 'consulta',
	'consulta em carater de urgencia pela oftalmologista' : '',
	'realizou consulta com a hematologista' : 'consulta',
	'realizou consulta com infectologista' : 'consulta',
	'realizou consulta medica - infectologista' : 'consulta',
	'realizou consulta com reumatologista v' : 'consulta',
	'realizou consulta com dra. poliana oncologista' : 'consulta',
	'realizado consulta com ginecologista' : 'consulta',
	'realizou consulta com dra. socorro-hematologista' : 'consulta',
	'realizou consulta com a dra. karine – reumatologista ' : 'consulta',
	'realizou consulta com dra rosangela -hematologista' : 'consulta',
	'foi avaliado pela oftalmologista' : 'consulta',
	'foi avaliado pelo oftalmologista' : 'consulta',
	'realizou consulta com\ndermatologista' : 'consulta',
	'realizado consulta com oncologista' : 'consulta',
	'realizou consulta com hematologista' : 'consulta',
	'consulta em carater de urgencia com oftalmologista  ' : 'urgência',
	'realizou consulta com oftalmologista' : 'consulta',
	'foi avaliada pelo        oftalmologista' : 'consulta',
	'realizou consulta com ginecologista' : 'consulta',
	'realizou consulta com cardiologista' : 'consulta',
	'realizou consulta com cardiologista cirurgiao pediatra ' : 'consulta',
	'realizou consulta com oftalmologista ' : 'consulta',
	'realizou consulta com ortopedista' : 'consulta',
	'realizou consulta com dr° andrey , dermatologista e exame fisico ' : 'consulta',
	'realizou consulta com dr. renildo –neurologista ' : 'consulta',
	'realizou consulta com infectologista pediatrico' : 'consulta',
	'realizou consulta com dr° andrey , demartologista' : 'consulta',
	'realizado consulta com neurologista ' : 'consulta',
	'avaliado oftalmologista' : 'consulta',
	'realizado consulta com infectologista ' : 'consulta',
	'foi atendida hematologista' : 'consulta',
	'realizou consulta ortopedista ' : 'consulta',
	'realizou consulta odontologista ' : 'consulta',
	'realizou consulta dermatologista ' : 'consulta',
	'realizou consulta com infectologista pediatra ' : 'consulta',
	'realizou consulta com (infectologista)' : 'consulta',
	'foi avaliado pela  hematologista' : 'consulta',
	'atendido pelo dermatologista' : 'consulta',
	'atendido pelo oftalmologista' : 'consulta',
	'realizou consulta de retorno com dra. silvia dermatologista' : 'consulta',
	'foi avaliada pelo gastroenterologista' : 'consulta',
	'realizou consulta de retorno gastroenterologista' : 'consulta',
	'realizou consulta de retorno com otorrinolaringologista' : 'consulta',
	'realizou consulta com dr. romulo neurologista' : 'consulta',
	'realizou consulta com dr. romulo -neurologista' : 'consulta',
	'realizou consulta com dra. gleide cardiologista' : 'consulta',
	'realizado consulta com ortopedista' : 'consulta',
	'avaliada pelo pneumologista' : 'consulta',
	'realizou consulta com urologista' : 'consulta',
	'realizou consulta com urologista cirurgiao' : 'consulta',
	'realizado consulta com cardiologista ' : 'consulta',
	'foi avaliado pelo neurologista' : 'consulta',
	'avaliado pelo ortopedista - traumatologista' : 'consulta',
	'realizou consulta cardiologista ' : 'consulta',
	'consulta com endocrinologista' : 'consulta',
	'realizou consulta com dr. wornei - infectologista' : 'consulta',
	'realizou consulta com oftalmologista' : 'consulta',
	'realizou consulta de retorno com oftalmologista' : 'consulta',
	'realizou a consulta com o pneumologista' : 'consulta',
	'realizado consulta pneumologista' : 'consulta',
	'realizado consulta neurologista' : 'consulta',
	'realizado consulta com dra. mariane-gastroenterologista' : 'consulta',
	'realizou consulta com cardiologista pediatra' : 'consulta',
	'realizou consulta com dr. elson- ortopedista' : 'consulta',
	'realizado avaliacao com ginecologista ' : 'consulta',
	'foi antecipada consulta com infectologista' : 'consulta',
	'ortopedista/curativo' : 'curativo',
	'onde realizou cirurgia de transplante pelo oftalmologista ' : 'procedimento cirúrgico',
	'realizou consulta oftalmologista' : 'consulta',
	'colostograma distal' : '?',
	'oncologista(radioterapia)' : '?',
	'realizou exame fisico pelo drº. osman – cardiologista' : 'exame',
}